// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SignalingClientConfigDto {
  final String baseUrl;
  final BigInt heartbeatIntervalSecs;

  const SignalingClientConfigDto({
    required this.baseUrl,
    required this.heartbeatIntervalSecs,
  });

  @override
  int get hashCode => baseUrl.hashCode ^ heartbeatIntervalSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignalingClientConfigDto &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          heartbeatIntervalSecs == other.heartbeatIntervalSecs;
}
