// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/connection.dart';
import 'api/models.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -232921867;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_application',
        ioDirectory: '../rust/crates/mobile-bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Map<String, ArcRtcDataChannel>
  crateApiTransferPeerConnectionHandleAutoAccessorGetDataChannels({
    required PeerConnectionHandle that,
  });

  ArcRtcPeerConnection crateApiTransferPeerConnectionHandleAutoAccessorGetPc({
    required PeerConnectionHandle that,
  });

  void crateApiTransferPeerConnectionHandleAutoAccessorSetDataChannels({
    required PeerConnectionHandle that,
    required Map<String, ArcRtcDataChannel> dataChannels,
  });

  void crateApiTransferPeerConnectionHandleAutoAccessorSetPc({
    required PeerConnectionHandle that,
    required ArcRtcPeerConnection pc,
  });

  void crateApiTransferAddDataChannel({
    required String connectionId,
    required String label,
    required ArcRtcDataChannel dc,
  });

  Uint8List crateApiConnectionConnectionDecrypt({
    required String keyHex,
    required String ciphertextB64,
  });

  ConnectionInitLocalResult crateApiConnectionConnectionDeriveKeys({
    required String secretHex,
  });

  String crateApiConnectionConnectionEncrypt({
    required String keyHex,
    required List<int> plaintext,
  });

  ConnectionInitLocalResult crateApiConnectionConnectionInitLocal();

  String crateApiConnectionGenerateConnectionLink({
    required String baseUrl,
    required String rendezvousId,
    required String secret,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  SignalingClientConfigDto crateApiClientLoadSignalingClientConfig();

  SignalingClientConfigDto crateApiClientOverrideSignalingBaseUrl({
    required String url,
  });

  Future<void> crateApiTransferRegisterConnection({
    required String connectionId,
    required ArcRtcPeerConnection pc,
  });

  SignalingClientConfigDto crateApiClientResetSignalingClientConfig();

  void crateApiTransferStartFileReceive({
    required String connectionId,
    required String saveDir,
  });

  void crateApiTransferStartFileTransfer({
    required String connectionId,
    required String filePath,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcRtcDataChannel;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcRtcDataChannel;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRtcDataChannelPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcRtcPeerConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcRtcPeerConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRtcPeerConnectionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PeerConnectionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PeerConnectionHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PeerConnectionHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Map<String, ArcRtcDataChannel>
  crateApiTransferPeerConnectionHandleAutoAccessorGetDataChannels({
    required PeerConnectionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiTransferPeerConnectionHandleAutoAccessorGetDataChannelsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTransferPeerConnectionHandleAutoAccessorGetDataChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "PeerConnectionHandle_auto_accessor_get_data_channels",
        argNames: ["that"],
      );

  @override
  ArcRtcPeerConnection crateApiTransferPeerConnectionHandleAutoAccessorGetPc({
    required PeerConnectionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiTransferPeerConnectionHandleAutoAccessorGetPcConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTransferPeerConnectionHandleAutoAccessorGetPcConstMeta =>
      const TaskConstMeta(
        debugName: "PeerConnectionHandle_auto_accessor_get_pc",
        argNames: ["that"],
      );

  @override
  void crateApiTransferPeerConnectionHandleAutoAccessorSetDataChannels({
    required PeerConnectionHandle that,
    required Map<String, ArcRtcDataChannel> dataChannels,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
            that,
            serializer,
          );
          sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
            dataChannels,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiTransferPeerConnectionHandleAutoAccessorSetDataChannelsConstMeta,
        argValues: [that, dataChannels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTransferPeerConnectionHandleAutoAccessorSetDataChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "PeerConnectionHandle_auto_accessor_set_data_channels",
        argNames: ["that", "dataChannels"],
      );

  @override
  void crateApiTransferPeerConnectionHandleAutoAccessorSetPc({
    required PeerConnectionHandle that,
    required ArcRtcPeerConnection pc,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
            pc,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiTransferPeerConnectionHandleAutoAccessorSetPcConstMeta,
        argValues: [that, pc],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTransferPeerConnectionHandleAutoAccessorSetPcConstMeta =>
      const TaskConstMeta(
        debugName: "PeerConnectionHandle_auto_accessor_set_pc",
        argNames: ["that", "pc"],
      );

  @override
  void crateApiTransferAddDataChannel({
    required String connectionId,
    required String label,
    required ArcRtcDataChannel dc,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(label, serializer);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
            dc,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransferAddDataChannelConstMeta,
        argValues: [connectionId, label, dc],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferAddDataChannelConstMeta =>
      const TaskConstMeta(
        debugName: "add_data_channel",
        argNames: ["connectionId", "label", "dc"],
      );

  @override
  Uint8List crateApiConnectionConnectionDecrypt({
    required String keyHex,
    required String ciphertextB64,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyHex, serializer);
          sse_encode_String(ciphertextB64, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectionConnectionDecryptConstMeta,
        argValues: [keyHex, ciphertextB64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "connection_decrypt",
        argNames: ["keyHex", "ciphertextB64"],
      );

  @override
  ConnectionInitLocalResult crateApiConnectionConnectionDeriveKeys({
    required String secretHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secretHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_init_local_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectionConnectionDeriveKeysConstMeta,
        argValues: [secretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionDeriveKeysConstMeta =>
      const TaskConstMeta(
        debugName: "connection_derive_keys",
        argNames: ["secretHex"],
      );

  @override
  String crateApiConnectionConnectionEncrypt({
    required String keyHex,
    required List<int> plaintext,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyHex, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectionConnectionEncryptConstMeta,
        argValues: [keyHex, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "connection_encrypt",
        argNames: ["keyHex", "plaintext"],
      );

  @override
  ConnectionInitLocalResult crateApiConnectionConnectionInitLocal() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_init_local_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionConnectionInitLocalConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionInitLocalConstMeta =>
      const TaskConstMeta(debugName: "connection_init_local", argNames: []);

  @override
  String crateApiConnectionGenerateConnectionLink({
    required String baseUrl,
    required String rendezvousId,
    required String secret,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(rendezvousId, serializer);
          sse_encode_String(secret, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionGenerateConnectionLinkConstMeta,
        argValues: [baseUrl, rendezvousId, secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionGenerateConnectionLinkConstMeta =>
      const TaskConstMeta(
        debugName: "generate_connection_link",
        argNames: ["baseUrl", "rendezvousId", "secret"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  SignalingClientConfigDto crateApiClientLoadSignalingClientConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signaling_client_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientLoadSignalingClientConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientLoadSignalingClientConfigConstMeta =>
      const TaskConstMeta(
        debugName: "load_signaling_client_config",
        argNames: [],
      );

  @override
  SignalingClientConfigDto crateApiClientOverrideSignalingBaseUrl({
    required String url,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signaling_client_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientOverrideSignalingBaseUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientOverrideSignalingBaseUrlConstMeta =>
      const TaskConstMeta(
        debugName: "override_signaling_base_url",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiTransferRegisterConnection({
    required String connectionId,
    required ArcRtcPeerConnection pc,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
            pc,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransferRegisterConnectionConstMeta,
        argValues: [connectionId, pc],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferRegisterConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "register_connection",
        argNames: ["connectionId", "pc"],
      );

  @override
  SignalingClientConfigDto crateApiClientResetSignalingClientConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signaling_client_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientResetSignalingClientConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientResetSignalingClientConfigConstMeta =>
      const TaskConstMeta(
        debugName: "reset_signaling_client_config",
        argNames: [],
      );

  @override
  void crateApiTransferStartFileReceive({
    required String connectionId,
    required String saveDir,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(saveDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransferStartFileReceiveConstMeta,
        argValues: [connectionId, saveDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferStartFileReceiveConstMeta =>
      const TaskConstMeta(
        debugName: "start_file_receive",
        argNames: ["connectionId", "saveDir"],
      );

  @override
  void crateApiTransferStartFileTransfer({
    required String connectionId,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransferStartFileTransferConstMeta,
        argValues: [connectionId, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferStartFileTransferConstMeta =>
      const TaskConstMeta(
        debugName: "start_file_transfer",
        argNames: ["connectionId", "filePath"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcRtcDataChannel => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcRtcDataChannel => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcRtcPeerConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcRtcPeerConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PeerConnectionHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PeerConnectionHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ArcRtcDataChannel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcRtcDataChannelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcRtcPeerConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcRtcPeerConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerConnectionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerConnectionHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerConnectionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, ArcRtcDataChannel>
  dco_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  ArcRtcDataChannel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcRtcDataChannelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcRtcPeerConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcRtcPeerConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerConnectionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ConnectionInitLocalResult dco_decode_connection_init_local_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ConnectionInitLocalResult(
      rendezvousId: dco_decode_String(arr[0]),
      mailboxId: dco_decode_String(arr[1]),
      secret: dco_decode_String(arr[2]),
      kSig: dco_decode_String(arr[3]),
      kMac: dco_decode_String(arr[4]),
      sas: dco_decode_String(arr[5]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, ArcRtcDataChannel)>
  dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel,
        )
        .toList();
  }

  @protected
  (String, ArcRtcDataChannel)
  dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
        arr[1],
      ),
    );
  }

  @protected
  SignalingClientConfigDto dco_decode_signaling_client_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SignalingClientConfigDto(
      baseUrl: dco_decode_String(arr[0]),
      heartbeatIntervalSecs: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ArcRtcDataChannel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcRtcDataChannelImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcRtcPeerConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcRtcPeerConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerConnectionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerConnectionHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerConnectionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, ArcRtcDataChannel>
  sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
          deserializer,
        );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  ArcRtcDataChannel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcRtcDataChannelImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcRtcPeerConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcRtcPeerConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerConnectionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerConnectionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ConnectionInitLocalResult sse_decode_connection_init_local_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rendezvousId = sse_decode_String(deserializer);
    var var_mailboxId = sse_decode_String(deserializer);
    var var_secret = sse_decode_String(deserializer);
    var var_kSig = sse_decode_String(deserializer);
    var var_kMac = sse_decode_String(deserializer);
    var var_sas = sse_decode_String(deserializer);
    return ConnectionInitLocalResult(
      rendezvousId: var_rendezvousId,
      mailboxId: var_mailboxId,
      secret: var_secret,
      kSig: var_kSig,
      kMac: var_kMac,
      sas: var_sas,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, ArcRtcDataChannel)>
  sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, ArcRtcDataChannel)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  (String, ArcRtcDataChannel)
  sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
          deserializer,
        );
    return (var_field0, var_field1);
  }

  @protected
  SignalingClientConfigDto sse_decode_signaling_client_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_baseUrl = sse_decode_String(deserializer);
    var var_heartbeatIntervalSecs = sse_decode_u_64(deserializer);
    return SignalingClientConfigDto(
      baseUrl: var_baseUrl,
      heartbeatIntervalSecs: var_heartbeatIntervalSecs,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    ArcRtcDataChannel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcRtcDataChannelImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    ArcRtcPeerConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcRtcPeerConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerConnectionHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerConnectionHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerConnectionHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    Map<String, ArcRtcDataChannel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    ArcRtcDataChannel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcRtcDataChannelImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    ArcRtcPeerConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcRtcPeerConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerConnectionHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_connection_init_local_result(
    ConnectionInitLocalResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rendezvousId, serializer);
    sse_encode_String(self.mailboxId, serializer);
    sse_encode_String(self.secret, serializer);
    sse_encode_String(self.kSig, serializer);
    sse_encode_String(self.kMac, serializer);
    sse_encode_String(self.sas, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void
  sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    List<(String, ArcRtcDataChannel)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
        item,
        serializer,
      );
    }
  }

  @protected
  void
  sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    (String, ArcRtcDataChannel) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
      self.$2,
      serializer,
    );
  }

  @protected
  void sse_encode_signaling_client_config_dto(
    SignalingClientConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_u_64(self.heartbeatIntervalSecs, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class ArcRtcDataChannelImpl extends RustOpaque implements ArcRtcDataChannel {
  // Not to be used by end users
  ArcRtcDataChannelImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcRtcDataChannelImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcRtcDataChannel,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcRtcDataChannel,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcRtcDataChannelPtr,
  );
}

@sealed
class ArcRtcPeerConnectionImpl extends RustOpaque
    implements ArcRtcPeerConnection {
  // Not to be used by end users
  ArcRtcPeerConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcRtcPeerConnectionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_ArcRtcPeerConnection,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcRtcPeerConnection,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcRtcPeerConnectionPtr,
  );
}

@sealed
class PeerConnectionHandleImpl extends RustOpaque
    implements PeerConnectionHandle {
  // Not to be used by end users
  PeerConnectionHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PeerConnectionHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_PeerConnectionHandle,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_PeerConnectionHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_PeerConnectionHandlePtr,
  );

  Map<String, ArcRtcDataChannel> get dataChannels => RustLib.instance.api
      .crateApiTransferPeerConnectionHandleAutoAccessorGetDataChannels(
        that: this,
      );

  ArcRtcPeerConnection get pc => RustLib.instance.api
      .crateApiTransferPeerConnectionHandleAutoAccessorGetPc(that: this);

  set dataChannels(Map<String, ArcRtcDataChannel> dataChannels) => RustLib
      .instance
      .api
      .crateApiTransferPeerConnectionHandleAutoAccessorSetDataChannels(
        that: this,
        dataChannels: dataChannels,
      );

  set pc(ArcRtcPeerConnection pc) => RustLib.instance.api
      .crateApiTransferPeerConnectionHandleAutoAccessorSetPc(
        that: this,
        pc: pc,
      );
}
