// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Initialize a connection link (Client A)
/// Returns a mailbox ID and generates a rendezvous token
ConnectionInitLocalResult connectionInitLocal() =>
    RustLib.instance.api.crateApiConnectionConnectionInitLocal();

/// Generate a connection link URL
String generateConnectionLink({
  required String baseUrl,
  required String rendezvousId,
}) => RustLib.instance.api.crateApiConnectionGenerateConnectionLink(
  baseUrl: baseUrl,
  rendezvousId: rendezvousId,
);

class ConnectionInitLocalResult {
  final String rendezvousId;
  final String mailboxId;
  final String kSig;
  final String kMac;
  final String sas;

  const ConnectionInitLocalResult({
    required this.rendezvousId,
    required this.mailboxId,
    required this.kSig,
    required this.kMac,
    required this.sas,
  });

  @override
  int get hashCode =>
      rendezvousId.hashCode ^
      mailboxId.hashCode ^
      kSig.hashCode ^
      kMac.hashCode ^
      sas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionInitLocalResult &&
          runtimeType == other.runtimeType &&
          rendezvousId == other.rendezvousId &&
          mailboxId == other.mailboxId &&
          kSig == other.kSig &&
          kMac == other.kMac &&
          sas == other.sas;
}
