// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../shared/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

SignalingClientConfigDto loadSignalingClientConfig() =>
    RustLib.instance.api.crateApiClientLoadSignalingClientConfig();

SignalingClientConfigDto overrideSignalingBaseUrl({required String url}) =>
    RustLib.instance.api.crateApiClientOverrideSignalingBaseUrl(url: url);

SignalingClientConfigDto resetSignalingClientConfig() =>
    RustLib.instance.api.crateApiClientResetSignalingClientConfig();
