// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_provider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

void init() => RustLib.instance.api.crateApiShareInit();

List<SourceDescriptor> listShareSources() =>
    RustLib.instance.api.crateApiShareListShareSources();

ShareStartResult startShare({
  required String connectionId,
  required String sourceId,
  required ShareConfig config,
}) => RustLib.instance.api.crateApiShareStartShare(
  connectionId: connectionId,
  sourceId: sourceId,
  config: config,
);

enum BitratePreset { low, medium, high }

class ShareConfig {
  final int fps;
  final BitratePreset bitratePreset;

  const ShareConfig({required this.fps, required this.bitratePreset});

  @override
  int get hashCode => fps.hashCode ^ bitratePreset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareConfig &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          bitratePreset == other.bitratePreset;
}

class ShareStartResult {
  final bool trackPrepared;
  final bool renegotiationRequired;
  final bool dataChannelAvailable;

  const ShareStartResult({
    required this.trackPrepared,
    required this.renegotiationRequired,
    required this.dataChannelAvailable,
  });

  @override
  int get hashCode =>
      trackPrepared.hashCode ^
      renegotiationRequired.hashCode ^
      dataChannelAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareStartResult &&
          runtimeType == other.runtimeType &&
          trackPrepared == other.trackPrepared &&
          renegotiationRequired == other.renegotiationRequired &&
          dataChannelAvailable == other.dataChannelAvailable;
}

class SourceDescriptor {
  final String sourceId;
  final SourceKind kind;
  final String name;
  final int? width;
  final int? height;

  const SourceDescriptor({
    required this.sourceId,
    required this.kind,
    required this.name,
    this.width,
    this.height,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      kind.hashCode ^
      name.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceDescriptor &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          kind == other.kind &&
          name == other.name &&
          width == other.width &&
          height == other.height;
}

enum SourceKind { display, window }
