// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void startFileTransfer({
  required String connectionId,
  required String filePath,
}) => RustLib.instance.api.crateApiTransferStartFileTransfer(
  connectionId: connectionId,
  filePath: filePath,
);

Future<void> registerConnection({
  required String connectionId,
  required ArcRtcPeerConnection pc,
}) => RustLib.instance.api.crateApiTransferRegisterConnection(
  connectionId: connectionId,
  pc: pc,
);

void startFileReceive({
  required String connectionId,
  required String saveDir,
}) => RustLib.instance.api.crateApiTransferStartFileReceive(
  connectionId: connectionId,
  saveDir: saveDir,
);

void addDataChannel({
  required String connectionId,
  required String label,
  required ArcRtcDataChannel dc,
}) => RustLib.instance.api.crateApiTransferAddDataChannel(
  connectionId: connectionId,
  label: label,
  dc: dc,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < RTCDataChannel >>>
abstract class ArcRtcDataChannel implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < RTCPeerConnection >>>
abstract class ArcRtcPeerConnection implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerConnectionHandle>>
abstract class PeerConnectionHandle implements RustOpaqueInterface {
  Map<String, ArcRtcDataChannel> get dataChannels;

  ArcRtcPeerConnection get pc;

  set dataChannels(Map<String, ArcRtcDataChannel> dataChannels);

  set pc(ArcRtcPeerConnection pc);
}
